import { format } from 'date-fns';
import { 
  FileText, 
  Download, 
  Printer, 
  Clock, 
  User, 
  AlertCircle, 
  Handshake, 
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  Minus,
  Copy,
  FileDown
} from 'lucide-react';
import type { Call } from '../types';
import { cn } from '../utils/cn';
import { useState } from 'react';
import { generatePDF } from '../utils/pdfGenerator';

interface CallSummaryProps {
  call: Call;
}

// Format number with Kenyan locale
const formatKES = (amount: number) => {
  return new Intl.NumberFormat('en-KE').format(amount);
};

export function CallSummary({ call }: CallSummaryProps) {
  const [copied, setCopied] = useState(false);
  const { customer, extraction, summary, duration, startedAt, endedAt } = call;

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadTxt = () => {
    const content = generateTextSummary(call);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `call-summary-${customer.name.replace(/\s+/g, '-')}-${format(startedAt, 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = () => {
    generatePDF(call);
  };

  const handleCopyTranscript = () => {
    const transcript = call.transcript.map(t => t.text).join('\n');
    navigator.clipboard.writeText(transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const sentimentConfig = {
    positive: { icon: TrendingUp, color: 'text-green-600', bg: 'bg-green-100', label: 'Positive' },
    neutral: { icon: Minus, color: 'text-gray-600', bg: 'bg-gray-100', label: 'Neutral' },
    negative: { icon: TrendingDown, color: 'text-red-600', bg: 'bg-red-100', label: 'Negative' },
  };

  const sentConfig = sentimentConfig[extraction.sentiment];
  const SentIcon = sentConfig.icon;

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 overflow-hidden print:shadow-none print:border-0">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-6 py-4 print:bg-blue-600">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="w-6 h-6 text-white" />
            <div>
              <h2 className="text-xl font-bold text-white">Session Summary</h2>
              <p className="text-blue-100 text-sm">Auto-generated by AI</p>
            </div>
          </div>
          <div className="flex gap-2 print:hidden">
            <button
              onClick={handleCopyTranscript}
              className="flex items-center gap-2 px-3 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm transition-colors"
            >
              <Copy className="w-4 h-4" />
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 px-3 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm transition-colors"
            >
              <FileDown className="w-4 h-4" />
              PDF
            </button>
            <button
              onClick={handleDownloadTxt}
              className="flex items-center gap-2 px-3 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm transition-colors"
            >
              <Download className="w-4 h-4" />
              TXT
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-3 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm transition-colors"
            >
              <Printer className="w-4 h-4" />
              Print
            </button>
          </div>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Call Info Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <InfoCard
            icon={User}
            label="Customer"
            value={customer.name}
          />
          <InfoCard
            icon={Clock}
            label="Duration"
            value={formatDuration(duration)}
          />
          <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
              <span className="text-xs font-bold">KES</span>
              <span className="text-xs">Debt Amount</span>
            </div>
            <p className="font-semibold text-gray-900 dark:text-white truncate">
              KES {formatKES(customer.debtAmount)}
            </p>
          </div>
          <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
              <SentIcon className="w-4 h-4" />
              <span className="text-xs">Sentiment</span>
            </div>
            <div className="flex items-center gap-2">
              <span className={cn('px-2 py-0.5 rounded-full text-sm font-medium', sentConfig.bg, sentConfig.color)}>
                {sentConfig.label}
              </span>
              <span className="text-sm text-gray-600 dark:text-gray-300">{extraction.sentimentScore}%</span>
            </div>
          </div>
        </div>

        {/* Call Details */}
        <div className="text-sm text-gray-500 dark:text-gray-400 flex flex-wrap gap-4">
          <span>Date: {format(startedAt, 'MMMM d, yyyy')}</span>
          <span>Time: {format(startedAt, 'h:mm a')} - {endedAt ? format(endedAt, 'h:mm a') : 'N/A'}</span>
          <span>Account: {customer.accountNumber}</span>
        </div>

        {/* Full Transcript */}
        {call.transcript.length > 0 && (
          <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-4">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Full Transcript</h3>
            <div className="max-h-48 overflow-y-auto text-sm text-gray-700 dark:text-gray-300 space-y-2">
              {call.transcript.map((entry) => (
                <p key={entry.id} className="leading-relaxed">
                  {entry.text}
                </p>
              ))}
            </div>
          </div>
        )}

        {/* Summary Text */}
        {summary && (
          <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border-l-4 border-blue-500">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Summary</h3>
            <p className="text-gray-700 dark:text-gray-300">{summary.summaryText}</p>
          </div>
        )}

        {/* Extraction Details */}
        <div className="grid md:grid-cols-3 gap-4">
          {/* Promises */}
          <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-green-600 dark:text-green-400 font-bold text-sm">KES</span>
              <h3 className="font-semibold text-green-800 dark:text-green-300">Promises Made</h3>
            </div>
            {extraction.promises.length > 0 ? (
              <ul className="space-y-2">
                {extraction.promises.map((promise) => (
                  <li key={promise.id} className="text-sm text-gray-700 dark:text-gray-300">
                    <CheckCircle2 className="w-4 h-4 text-green-500 inline mr-2" />
                    {promise.description}
                    {promise.amount && (
                      <span className="ml-2 font-semibold text-green-600 dark:text-green-400">
                        KES {formatKES(promise.amount)}
                      </span>
                    )}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-gray-500 dark:text-gray-400">No promises made</p>
            )}
          </div>

          {/* Objections */}
          <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3">
              <AlertCircle className="w-5 h-5 text-yellow-600 dark:text-yellow-400" />
              <h3 className="font-semibold text-yellow-800 dark:text-yellow-300">Objections Raised</h3>
            </div>
            {extraction.objections.length > 0 ? (
              <ul className="space-y-2">
                {extraction.objections.map((objection) => (
                  <li key={objection.id} className="text-sm">
                    <span className={cn(
                      'text-xs px-1.5 py-0.5 rounded mr-2 capitalize',
                      objection.severity === 'high' && 'bg-red-100 text-red-700',
                      objection.severity === 'medium' && 'bg-yellow-100 text-yellow-700',
                      objection.severity === 'low' && 'bg-gray-100 text-gray-700'
                    )}>
                      {objection.severity}
                    </span>
                    <span className="text-gray-700 dark:text-gray-300">{objection.description}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-gray-500 dark:text-gray-400">No objections raised</p>
            )}
          </div>

          {/* Agreements */}
          <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3">
              <Handshake className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              <h3 className="font-semibold text-blue-800 dark:text-blue-300">Agreements Reached</h3>
            </div>
            {extraction.agreements.length > 0 ? (
              <ul className="space-y-2">
                {extraction.agreements.map((agreement) => (
                  <li key={agreement.id} className="text-sm text-gray-700 dark:text-gray-300">
                    <span className="text-xs bg-blue-100 dark:bg-blue-800 text-blue-700 dark:text-blue-200 px-1.5 py-0.5 rounded mr-2 capitalize">
                      {agreement.type.replace('_', ' ')}
                    </span>
                    {agreement.details}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-gray-500 dark:text-gray-400">No agreements reached</p>
            )}
          </div>
        </div>

        {/* Next Actions */}
        {summary && summary.nextActions.length > 0 && (
          <div className="border-t border-gray-200 dark:border-gray-700 pt-4">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-indigo-500" />
              Recommended Next Actions
            </h3>
            <div className="flex flex-wrap gap-2">
              {summary.nextActions.map((action, i) => (
                <span
                  key={i}
                  className="px-3 py-1.5 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 rounded-full text-sm"
                >
                  {action}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Key Quotes */}
        {extraction.keyQuotes.length > 0 && (
          <div className="border-t border-gray-200 dark:border-gray-700 pt-4">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-3">Key Quotes</h3>
            <div className="space-y-2">
              {extraction.keyQuotes.map((quote, i) => (
                <blockquote
                  key={i}
                  className="text-gray-600 dark:text-gray-400 italic border-l-3 border-purple-400 pl-4 py-1"
                >
                  "{quote}"
                </blockquote>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

interface InfoCardProps {
  icon: typeof User;
  label: string;
  value: string;
}

function InfoCard({ icon: Icon, label, value }: InfoCardProps) {
  return (
    <div className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-3">
      <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400 mb-1">
        <Icon className="w-4 h-4" />
        <span className="text-xs">{label}</span>
      </div>
      <p className="font-semibold text-gray-900 dark:text-white truncate">{value}</p>
    </div>
  );
}

function generateTextSummary(call: Call): string {
  const { customer, extraction, summary, duration, startedAt, endedAt, transcript } = call;
  const lines: string[] = [];

  const formatKESLocal = (amount: number) => {
    return new Intl.NumberFormat('en-KE').format(amount);
  };

  lines.push('='.repeat(60));
  lines.push('SESSION SUMMARY REPORT');
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(`Customer: ${customer.name}`);
  lines.push(`Account: ${customer.accountNumber}`);
  lines.push(`Phone: ${customer.phone}`);
  lines.push(`Debt Amount: KES ${formatKESLocal(customer.debtAmount)}`);
  lines.push('');
  lines.push(`Date: ${format(startedAt, 'MMMM d, yyyy')}`);
  lines.push(`Time: ${format(startedAt, 'h:mm a')} - ${endedAt ? format(endedAt, 'h:mm a') : 'N/A'}`);
  lines.push(`Duration: ${Math.floor(duration / 60)}m ${duration % 60}s`);
  lines.push(`Sentiment: ${extraction.sentiment} (${extraction.sentimentScore}%)`);
  lines.push('');

  lines.push('-'.repeat(60));
  lines.push('FULL TRANSCRIPT');
  lines.push('-'.repeat(60));
  transcript.forEach((entry) => {
    lines.push(entry.text);
  });
  lines.push('');

  lines.push('-'.repeat(60));
  lines.push('SUMMARY');
  lines.push('-'.repeat(60));
  lines.push(summary?.summaryText || 'No summary available');
  lines.push('');

  if (extraction.promises.length > 0) {
    lines.push('-'.repeat(60));
    lines.push('PROMISES MADE');
    lines.push('-'.repeat(60));
    extraction.promises.forEach((p) => {
      lines.push(`• ${p.description}`);
      if (p.amount) lines.push(`  Amount: KES ${formatKESLocal(p.amount)}`);
      if (p.dueDate) lines.push(`  Due Date: ${p.dueDate}`);
    });
    lines.push('');
  }

  if (extraction.objections.length > 0) {
    lines.push('-'.repeat(60));
    lines.push('OBJECTIONS RAISED');
    lines.push('-'.repeat(60));
    extraction.objections.forEach((o) => {
      lines.push(`• [${o.severity.toUpperCase()}] ${o.type.replace('_', ' ')}`);
      lines.push(`  ${o.description}`);
    });
    lines.push('');
  }

  if (extraction.agreements.length > 0) {
    lines.push('-'.repeat(60));
    lines.push('AGREEMENTS REACHED');
    lines.push('-'.repeat(60));
    extraction.agreements.forEach((a) => {
      lines.push(`• [${a.type.replace('_', ' ').toUpperCase()}] ${a.details}`);
    });
    lines.push('');
  }

  if (summary && summary.nextActions.length > 0) {
    lines.push('-'.repeat(60));
    lines.push('RECOMMENDED NEXT ACTIONS');
    lines.push('-'.repeat(60));
    summary.nextActions.forEach((action) => {
      lines.push(`• ${action}`);
    });
    lines.push('');
  }

  lines.push('='.repeat(60));
  lines.push(`Generated: ${format(new Date(), 'MMMM d, yyyy h:mm a')}`);
  lines.push('='.repeat(60));

  return lines.join('\n');
}
